name: Build Cross Platform App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install py_to_app
      - name: Build app
        run: py_to_app .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_app_${{ matrix.os }}
          path: dist/
