name: Build Tkinter App

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install PyInstaller
        run: pip install pyinstaller

      # macOS/Linux build
      - name: Build executable (macOS/Linux)
        if: runner.os != 'Windows'
        run: pyinstaller --onefile --add-data "image.png:." ui.py

      # Windows build
      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onefile --add-data "image.png;." ui.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-${{ matrix.os }}
          path: dist/
