name: Build Tkinter App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install matplotlib numpy scipy Pillow

      - name: Ensure Matplotlib cache folder exists
        run: |
          mkdir -p ~/.cache/matplotlib
          mkdir -p ~/.matplotlib
          
      - name: Pre-warm Matplotlib font cache
        run: |
          python -c "import matplotlib.pyplot as plt; plt.figure(); plt.plot(); plt.close()"

      # macOS/Linux build
      - name: Build executable (macOS/Linux)
        if: runner.os != 'Windows'
        run: |
          CACHE_DIR=$(python -c "import matplotlib; print(matplotlib.get_cachedir())")
          echo "Matplotlib cache: $CACHE_DIR"
          pyinstaller --onedir --windowed \
            --add-data "logo.png:." \
            --add-data "$CACHE_DIR:matplotlib_cache" \
            ui.py

      # Windows build
      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $cacheDir = python -c "import matplotlib; print(matplotlib.get_cachedir())"
          echo "Matplotlib cache is at $cacheDir"
          pyinstaller --onefile --noconsole `
            --add-data "logo.png;." `
            --add-data "$cacheDir;matplotlib_cache" `
            ui.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-${{ matrix.os }}
          path: dist/
