name: Build Tkinter App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest   # for py_to_app (macOS GUI)
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install py_to_app

      - name: Build app
        run: py_to_app main.py --include image.png --name "MyApp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-mac
          path: dist/
